In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows' , None);
pd.set_option('display.max_columns' , None);

In [3]:
df = pd.read_csv('flats.csv')
df.sample(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
3004,4 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,Sare Green ParC Phase 3,1.08 Crore,"₹ 5,150/sq.ft.",Super Built up area 2090(194.17 sq.m.),4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,NaN,16th of 19 Floors,NaN,0 to 1 Year Old,"['Huda Metro Station', 'Sector Road', 'Delhi-J...",Only end user and buyers to contact. Flat in r...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Safety3 out of 5', 'Lifestyle4 out of 5', 'E...",A46782853
897,4 BHK Flat in Sector 104 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,ATS Triumph3.9 ★,2.6 Crore,"₹ 8,813/sq.ft.",Super Built up area 3150(292.64 sq.m.)Carpet a...,4 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"16th, Sector 104 Gurgaon, Gurgaon, Haryana",16th of 27 Floors,East,1 to 5 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...","This 4 bhk flat is located in ats triumph, whi...","['6 Fan', '1 Exhaust Fan', '16 Light', '6 AC',...","['Water purifier', 'Security / Fire Alarm', 'F...","['Green Area4 out of 5', 'Construction5 out of...",Y69218718
1429,3 BHK Flat in Sector 102 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Adani M2K Oyster Grande3.9 ★,2.61 Crore,"₹ 10,046/sq.ft.",Super Built up area 2598(241.36 sq.m.)Built Up...,3 Bedrooms,3 Bathrooms,3 Balconies,"Study Room,Servant Room","Flat, Sector 102 Gurgaon, Gurgaon, Haryana",14th of 24 Floors,North-East,1 to 5 Year Old,"['WTC Plaza', 'Star Mall', 'Dwarka Expy, Dhanw...",Looking for a 3 bhk property for sale in gurga...,"['5 AC', '1 Chimney', 'No Bed', 'No Curtains',...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction4.5 out ...",I70030056
153,3 BHK Flat in Garauli Kalan,https://www.99acres.com/3-bhk-bedroom-apartmen...,ashiyara 2,45 Lac,"₹ 4,500/sq.ft.",Super Built up area 1000(92.9 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Garauli Kalan, Gurgaon, Haryana",18th of 19 Floors,NaN,Jan 2025,"['Shri Balaji Hospital and Trauma Center', 'Ka...",Residential apartment for sell.The property ha...,NaN,NaN,NaN,Y68479394
2445,2 BHK Flat in Sector 86 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Ansal Heights 86,82 Lac,"₹ 6,029/sq.ft.",Super Built up area 1360(126.35 sq.m.)Built Up...,2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Sector 86 Gurgaon, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['IRIS Broadway Mall', 'Delhi Jaipur Expresswa...",2bhk ready to move flat in ansal heights secto...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Lifestyle5 out of 5...",E63659868

In [4]:
print(df.duplicated().sum());

0

In [5]:
print(df.isnull().sum());

property_name         0
link                  0
society               1
price                10
area                 13
areaWithType          9
bedRoom               9
bathroom              9
balcony               9
additionalRoom     1323
address              15
floorNum             11
facing              890
agePossession        10
nearbyLocations     104
description           9
furnishDetails      814
features            423
rating              341
property_id           9
dtype: int64

In [6]:
df.drop(columns = ['link' , 'property_id'] , inplace = True);

In [7]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [8]:
df.rename(columns = {'area':'price_per_sqft'} , inplace = True);
df.head();

In [9]:
df.society.value_counts().shape

(638,)

In [10]:
import re
df['society'] = df['society'].apply(lambda name : re.sub(r'\d+(\.\d+)?\s?★','',str(name)).strip()).str.lower();

In [11]:
df['society'].value_counts()

society
tulip violet                                     75
ss the leaf                                      74
shapoorji pallonji joyville gurugram             45
dlf new town heights                             38
signature global park                            36
shree vardhman victoria                          35
emaar mgf emerald floors premier                 32
smart world gems                                 32
smart world orchard                              32
paras dews                                       31
dlf the ultima                                   31
dlf regal gardens                                30
m3m woodshire                                    30
shree vardhman flora                             29
signature global solera                          28
la vida by tata housing                          28
godrej nature plus                               27
bptp terra                                       25
emaar gurgaon greens                             25
vatika gurgaon                                   24
experion the heartsong                           24
eldeco accolade                                  24
bestech park view residency                      23
m3m heights                                      22
emaar palm gardens                               22
ats triumph                                      22
tata primanti                                    22
rof ananda                                       21
sare crescent parc                               21
godrej                                           21
experion windchants                              20
antriksh heights                                 19
sare homes                                       19
mapsko mount ville                               18
indiabulls centrum park                          18
ambience creacions                               18
m3m golfestate                                   18
chd avenue                                       18
ats tourmaline                                   18
m3m skywalk                                      18
hcbs sports ville                                18
sobha city                                       18
supertech araville                               18
godrej summit                                    17
pareena coban residences                         17
conscient heritage max                           17
gls arawali homes                                17
m3m merlin                                       16
bestech park view grand spa                      16
umang monsoon breeze                             15
ramsons kshitij                                  15
godrej oasis                                     15
dlf the skycourt                                 15
ansal heights 86                                 15
emaar mgf the palm drive                         15
corona optus                                     14
ireo victory valley                              14
the close north                                  14
imperia the esfera                               14
vatika the seven lamps                           14
dlf the primus                                   14
ireo skyon                                       14
bestech park view ananda                         14
orchid petals                                    14
mvn athens                                       14
umang winter hills                               14
indiabulls enigma                                14
central park flower valley                       13
ireo the corridors                               13
puri diplomatic greens                           13
puri emerald bay                                 13
ats kocoon                                       13
alpha corp gurgaonone                            11
bestech park view sanskruti                      11
breez global hill view                           11
tarc maceo                                       11
sbtl caladium                                    11
adani m2k oyster grande                          11
dlf regency park                                 11
m3m soulitude                                    11
raheja vedaanta                                  11
breez global heights                             11
godrej aria                                      11
emaar mgf palm hills                             10
pyramid urban homes 2                            10
ild greens                                       10
pivotal devaan                                   10
godrej air                                       10
ramprastha the edge towers                       10
zara aavaas                                      10
signature global synera                          10
capital residences 360                           10
aipl the peaceful homes                           9
parsvnath green ville                             9
vatika city                                       9
microtek greenburg                                9
pareena mi casa                                   9
bestech park view city                            9
avl 36 gurgaon                                    8
m3m capital                                       8
the lions cghs                                    8
birla navya                                       8
bestech altura                                    8
orris aster court premier                         8
emaar digihomes                                   8
ss                                                8
assotech blith                                    8
gls avenue 51                                     8
tulip ivory                                       8
vatika lifestyle homes                            8
m3m skycity                                       8
ansal housing highland park                       7
signature global orchard avenue                   7
ireo the grand arch                               7
sidhartha ncr one phase                           7
signature andour heights                          7
aipl zen residences                               7
orris carnation residency                         7
mapsko casa bella                                 7
sare crescent parc royal greens phase 1           7
signature global city                             7
emaar imperial gardens                            7
sare green parc phase 3                           7
vipul lavanya                                     7
trisara our homes 3                               7
ashiana anmol                                     7
bptp astaire gardens                              6
pyramid urban                                     6
supertech hues                                    6
signature the roselia                             6
green court                                       6
hero homes                                        6
parsvnath exotica                                 6
bestech park view spa next                        6
greenopolis                                       6
kiran residency                                   6
pioneer araya                                     6
m3m sierra 68                                     6
ashiana mulberry                                  6
mapsko royale ville                               6
suncity vatsal valley                             6
signature global park 4                           6
hsiidc sidco aravali                              6
signature global city 63a                         6
central park flower valley aqua front towers      5
signature global grand iva                        5
godrej habitat                                    5
signature global city 81                          5
unitech fresco                                    5
vatika sovereign park                             5
conscient elevate                                 5
ats marigold                                      5
tulip monsella                                    5
adani brahma samsara vilasa                       5
signature global city 37d ph 2                    5
pareena laxmi apartments                          5
satya the hermitage                               5
signature global the millennia                    5
m3m the marina                                    5
pioneer park                                      5
krisumi waterfall residences                      5
emaar mgf emerald estate                          5
central park resorts                              5
silverglades the melia                            5
signature global city 92                          5
unitech uniworld gardens                          5
essel towers                                      5
dlf park place                                    5
ireo uptown                                       5
vatika city homes                                 5
apna enclave                                      5
ild grand                                         4
raheja navodaya                                   4
ramprastha skyz                                   4
unitech vistas                                    4
signature the serenas                             4
railway officers rpf society                      4
afnhb jalvayu vihar                               4
lotus homz                                        4
dlf the arbour                                    4
hsiidc sidco shivalik apartments                  4
ramprastha primera                                4
godrej icon                                       4
krrish provence estate                            4
global hill view                                  4
kendriya vihar                                    4
essel tower                                       4
sare petioles                                     4
corona gracieux                                   4
emaar palm heights                                4
ss the coralwood                                  4
prime habitat                                     4
orris aster court                                 4
godrej frontier                                   4
tata gurgaon gateway                              4
unitech sunbreeze                                 3
brisk lumbini terrace homes                       3
smriti apartment                                  3
dlf carlton estate                                3
pivotal riddhi siddhi                             3
sidhartha ncr one                                 3
raheja sampada                                    3
pyramid elite                                     3
signature global solera 2                         3
my home                                           3
tulip petals                                      3
sare green parc 2                                 3
dlf express greens                                3
spaze privvy the address                          3
shri ram apartments                               3
spaze privy                                       3
raheja revanta                                    3
tulip lemon                                       3
conscient habitat                                 3
guru gram haryana cghs                            3
dhoot time residency                              3
sunischit apartments                              3
vatika xpressions                                 3
mahindra aura                                     3
bhagwati sadan                                    3
valley view estate                                3
siddhartha apartment                              3
dlf royalton tower                                3
the roselia 2                                     3
satya element one                                 3
apex our homes                                    3
spaze privy at                                    3
suncity platinum towers                           3
vatika independent floors                         3
shri banke bihari society                         3
whiteland blissville                              3
aipl club residences                              3
maxworth city residences                          3
dlf belvedere towers                              3
paras quartier                                    3
unitech the residences                            3
ambience lagoon                                   3
raheja atharva                                    3
krrish florence estate                            3
piedmont taksila heights                          3
sidhartha ncr greens                              3
deepak minda                                      3
unitech heritage city                             3
sapphire eighty three                             3
sukhshanti apartment                              3
tulip white                                       3
tulip purple                                      3
chintels paradiso                                 3
adani aangan arcade                               3
sare green parc                                   3
shree arihant apartment                           3
ss almeria                                        3
dlf the grove                                     3
puri the aravallis                                2
aqua front towers                                 2
today callidora                                   2
park royal apartment                              2
sahara grace                                      2
housing board colony                              2
bptp pedestal                                     2
mrg world ultimus                                 2
mapsko paradise                                   2
professors enclave cghs                           2
breeze global heights                             2
dlf city                                          2
ramprastha the atrium                             2
shapoorji pallonji joyville                       2
dlf the icon                                      2
element one service                               2
silverglades hightown residences                  2
nbcc heights                                      2
suncity heights                                   2
ambience caitriona                                2
surendra avenue 69                                2
jammu and kashmir bank employees cghs             2
sidhivinayak apartments                           2
oriental valley chs                               2
emaar mgf emerald floors                          2
maruti vihar                                      2
raheja atlantis                                   2
central park 2 bellevue                           2
tulip orange                                      2
adani aangan galleria                             2
milan cghs 9                                      2
ansal api celebrity suites                        2
cghs airport apartment                            2
ansal heights                                     2
m3m urbana                                        2
vatika inxt floors                                2
palam vihar society                               2
m3m latitude                                      2
pioneer urban presidia                            2
elan the presidential                             2
lagoon apartment                                  2
rof aalayas                                       2
signature global the millennia 3                  2
m3m sky lofts                                     2
vasant appartments                                2
shree shyam residency                             2
shyam apartment                                   2
ansal api esencia                                 2
mahindra luminare                                 2
bptp freedom park life                            2
the close south                                   2
landmark the residency                            2
awho shanti vihar                                 2
raheja vanya                                      2
godrej nature plus serenity                       2
suncity avenue 76                                 2
supertech hill town                               2
vipul world floors                                2
viridian the plaza 106                            2
ss hibiscus                                       2
the penthouses at the hibiscus                    2
bestech spa signature                             2
emaar mgf palm studios                            2
vatika emilia floors                              2
tulip leaf                                        2
ardee city                                        2
residency grand                                   2
ss residency                                      2
om appartments                                    2
suposhaa smartworld orchard                       2
mittal surya vihar                                2
supertech hilltown                                2
ganga apartment                                   2
apartment                                         2
lavanya apartments                                2
samaspurkunj                                      2
ramprastha city                                   2
orchid island                                     2
dlf the crest                                     2
green campus chs                                  2
suncity avenue                                    2
dlf the belaire                                   2
paras irene                                       2
bptp amstoria                                     2
m3m ikonic                                        2
vipul belmonte                                    2
emaar mgf the enclave                             2
bptp mansions park prime                          2
tulsiani easy in homes                            2
spire woods now ananda by alpha corp              1
maa bhagwati residency                            1
parkwood westend                                  1
signature global infinity mall                    1
the cocoon                                        1
divya apartments                                  1
ansals highland park                              1
ild grand centra                                  1
sobha smriti apartments                           1
conscient one                                     1
emaar palm premier                                1
lig flat                                          1
aditya apartment                                  1
ramprasta awho                                    1
maple heights                                     1
ikon tower baani city centre                      1
mittal cosmos executive apartments                1
ansal harmony homes                               1
shree balaji appartment                           1
ashok vihar phase 2                               1
central park flower valley cerise floors          1
lord krishna                                      1
unitech harmony                                   1
.                                                 1
emaar mgf palm terraces select                    1
hector trimurti heights                           1
unitech uniworld city                             1
bhawna cghs                                       1
ompee k s residency                               1
apex builders                                     1
central park resort belgravia residences          1
the serenas                                       1
the new people apartments                         1
chanderlok society                                1
ansal estella                                     1
laxmi apartment sector 99a gurgaon                1
sanskriti apartments                              1
millenia                                          1
emaar emerald hills                               1
ansal maple heights                               1
the nav manesar apartment                         1
signature global orchard avenue 2                 1

In [12]:
df = df[df['price'] != 'Price on Request']

In [13]:
def treat_price(x):
    if type(x) == float:
        return x;
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100 , 2);
        else:
            return round(float(x[0]),2);

In [14]:
df['price'] = df['price'].str.split(' ').apply(treat_price);

In [15]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [18]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹' , '').str.replace(',' , '').str.strip().astype('float');

In [19]:
df.head(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [20]:
df['areaWithType'].value_counts()

areaWithType
Super Built up area 1350(125.42 sq.m.)                                                                                          17
Super Built up area 1578(146.6 sq.m.)                                                                                           17
Super Built up area 1950(181.16 sq.m.)Carpet area: 1161 sq.ft. (107.86 sq.m.)                                                   17
Super Built up area 1650(153.29 sq.m.)Carpet area: 1022.58 sq.ft. (95 sq.m.)                                                    15
Super Built up area 2010(186.74 sq.m.)                                                                                          14
Super Built up area 2150(199.74 sq.m.)                                                                                          12
Carpet area: 1650 (153.29 sq.m.)                                                                                                11
Super Built up area 1950(181.16 sq.m.)                                                                                          11
Super Built up area 1650(153.29 sq.m.)                                                                                          10
Super Built up area 1550(144 sq.m.)                                                                                             10
Carpet area: 1150 (106.84 sq.m.)                                                                                                10
Super Built up area 1920(178.37 sq.m.)                                                                                          10
Carpet area: 1450 (134.71 sq.m.)                                                                                                 9
Super Built up area 1828(169.83 sq.m.)                                                                                           9
Super Built up area 1640(152.36 sq.m.)                                                                                           9
Carpet area: 489 (45.43 sq.m.)                                                                                                   9
Carpet area: 1350 (125.42 sq.m.)                                                                                                 9
Carpet area: 1950 (181.16 sq.m.)                                                                                                 8
Carpet area: 900 (83.61 sq.m.)                                                                                                   8
Carpet area: 2400 (222.97 sq.m.)                                                                                                 8
Carpet area: 1800 (167.23 sq.m.)                                                                                                 8
Super Built up area 1760(163.51 sq.m.)Built Up area: 1186 sq.ft. (110.18 sq.m.)Carpet area: 1130 sq.ft. (104.98 sq.m.)           8
Super Built up area 1366(126.91 sq.m.)                                                                                           8
Carpet area: 750 (69.68 sq.m.)                                                                                                   8
Super Built up area 1200(111.48 sq.m.)                                                                                           7
Super Built up area 1930(179.3 sq.m.)                                                                                            7
Super Built up area 2364(219.62 sq.m.)                                                                                           7
Super Built up area 3400(315.87 sq.m.)                                                                                           7
Carpet area: 1600 (148.64 sq.m.)                                                                                                 7
Super Built up area 1538(142.88 sq.m.)                                                                                           7
Super Built up area 2200(204.39 sq.m.)                                                                                           7
Super Built up area 2350(218.32 sq.m.)                                                                                           7
Super Built up area 1415(131.46 sq.m.)                                                                                           7
Carpet area: 1103 (102.47 sq.m.)                                                                                                 7
Carpet area: 1300 (120.77 sq.m.)                                                                                                 7
Carpet area: 1760 (163.51 sq.m.)                                                                                                 7
Carpet area: 2300 (213.68 sq.m.)                                                                                                 7
Super Built up area 2408(223.71 sq.m.)                                                                                           7
Super Built up area 2100(195.1 sq.m.)                                                                                            7
Super Built up area 2727(253.35 sq.m.)                                                                                           6
Super Built up area 1750(162.58 sq.m.)                                                                                           6
Carpet area: 1423 (132.2 sq.m.)                                                                                                  6
Carpet area: 1326 (123.19 sq.m.)                                                                                                 6
Super Built up area 1572(146.04 sq.m.)                                                                                           6
Super Built up area 1568(145.67 sq.m.)                                                                                           6
Super Built up area 2290(212.75 sq.m.)                                                                                           6
Carpet area: 822 (76.37 sq.m.)                                                                                                   6
Super Built up area 3150(292.64 sq.m.)                                                                                           6
Super Built up area 2812(261.24 sq.m.)                                                                                           6
Carpet area: 700 (65.03 sq.m.)                                                                                                   6
Super Built up area 2215(205.78 sq.m.)                                                                                           6
Carpet area: 1200 (111.48 sq.m.)                                                                                                 5
Carpet area: 1975 (183.48 sq.m.)                                                                                                 5
Carpet area: 2000 (185.81 sq.m.)                                                                                                 5
Super Built up area 1435(133.32 sq.m.)                                                                                           5
Super Built up area 1700(157.94 sq.m.)                                                                                           5
Super Built up area 1245(115.66 sq.m.)                                                                                           5
Super Built up area 1970(183.02 sq.m.)                                                                                           5
Super Built up area 2000(185.81 sq.m.)                                                                                           5
Super Built up area 1000(92.9 sq.m.)                                                                                             5
Built Up area: 700 (65.03 sq.m.)                                                                                                 5
Super Built up area 1975(183.48 sq.m.)                                                                                           5
Super Built up area 1360(126.35 sq.m.)                                                                                           5
Carpet area: 1050 (97.55 sq.m.)                                                                                                  5
Super Built up area 1215(112.88 sq.m.)                                                                                           5
Super Built up area 1457(135.36 sq.m.)Carpet area: 849 sq.ft. (78.87 sq.m.)                                                      5
Super Built up area 2149(199.65 sq.m.)                                                                                           5
Super Built up area 2025(188.13 sq.m.)                                                                                           5
Super Built up area 1960(182.09 sq.m.)                                                                                           5
Super Built up area 1480(137.5 sq.m.)                                                                                            5
Super Built up area 1850(171.87 sq.m.)                                                                                           5
Carpet area: 450 (41.81 sq.m.)                                                                                                   5
Carpet area: 600 (55.74 sq.m.)                                                                                                   5
Super Built up area 1997(185.53 sq.m.)                                                                                           5
Carpet area: 850 (78.97 sq.m.)                                                                                                   5
Carpet area: 645 (59.92 sq.m.)                                                                                                   5
Super Built up area 1565(145.39 sq.m.)                                                                                           5
Super Built up area 2812(261.24 sq.m.)Built Up area: 2600 sq.ft. (241.55 sq.m.)Carpet area: 2400 sq.ft. (222.97 sq.m.)           5
Super Built up area 1875(174.19 sq.m.)                                                                                           5
Super Built up area 1100(102.19 sq.m.)                                                                                           4
Super Built up area 1081(100.43 sq.m.)                                                                                           4
Super Built up area 1900(176.52 sq.m.)                                                                                           4
Super Built up area 650(60.39 sq.m.)                                                                                             4
Super Built up area 2355(218.79 sq.m.)Built Up area: 1535 sq.ft. (142.61 sq.m.)Carpet area: 1403 sq.ft. (130.34 sq.m.)           4
Super Built up area 1103(102.47 sq.m.)                                                                                           4
Super Built up area 1790(166.3 sq.m.)                                                                                            4
Built Up area: 2040 (189.52 sq.m.)                                                                                               4
Super Built up area 1430(132.85 sq.m.)                                                                                           4
Super Built up area 1900(176.52 sq.m.)Carpet area: 1240.04 sq.ft. (115.2 sq.m.)                                                  4
Super Built up area 1780(165.37 sq.m.)                                                                                           4
Super Built up area 1261(117.15 sq.m.)                                                                                           4
Super Built up area 1385(128.67 sq.m.)Built Up area: 940 sq.ft. (87.33 sq.m.)Carpet area: 845 sq.ft. (78.5 sq.m.)                4
Super Built up area 1725(160.26 sq.m.)                                                                                           4
Super Built up area 1727(160.44 sq.m.)Carpet area: 1017 sq.ft. (94.48 sq.m.)                                                     4
Super Built up area 1365(126.81 sq.m.)                                                                                           4
Super Built up area 2400(222.97 sq.m.)                                                                                           4
Super Built up area 2545(236.44 sq.m.)                                                                                           4
Carpet area: 1250 (116.13 sq.m.)                                                                                                 4
Carpet area: 1500 (139.35 sq.m.)                                                                                                 4
Super Built up area 2191(203.55 sq.m.)                                                                                           4
Built Up area: 1103 (102.47 sq.m.)                                                                                               4
Super Built up area 600(55.74 sq.m.)                                                                                             4
Carpet area: 1225 (113.81 sq.m.)                                                                                                 4
Super Built up area 1825(169.55 sq.m.)                                                                                           4
Super Built up area 2358(219.07 sq.m.)                                                                                           4
Super Built up area 1789(166.2 sq.m.)                                                                                            4
Carpet area: 1549 (143.91 sq.m.)                                                                                                 4
Super Built up area 2950(274.06 sq.m.)                                                                                           4
Super Built up area 1900(176.52 sq.m.)Built Up area: 1600 sq.ft. (148.64 sq.m.)Carpet area: 1240.04 sq.ft. (115.2 sq.m.)         4
Super Built up area 1310(121.7 sq.m.)                                                                                            4
Super Built up area 1300(120.77 sq.m.)                                                                                           4
Super Built up area 1942(180.42 sq.m.)                                                                                           4
Carpet area: 2290 (212.75 sq.m.)                                                                                                 4
Super Built up area 2802(260.31 sq.m.)Built Up area: 2225.56 sq.ft. (206.76 sq.m.)                                               4
Carpet area: 501 (46.54 sq.m.)                                                                                                   4
Super Built up area 2095(194.63 sq.m.)                                                                                           4
Carpet area: 1400 (130.06 sq.m.)                                                                                                 4
Carpet area: 800 (74.32 sq.m.)                                                                                                   4
Built Up area: 1350 (125.42 sq.m.)                                                                                               4
Super Built up area 1457(135.36 sq.m.)                                                                                           4
Super Built up area 1930(179.3 sq.m.)Built Up area: 1929 sq.ft. (179.21 sq.m.)Carpet area: 1928 sq.ft. (179.12 sq.m.)            4
Carpet area: 1340 (124.49 sq.m.)                                                                                                 4
Super Built up area 2000(185.81 sq.m.)Built Up area: 1900 sq.ft. (176.52 sq.m.)Carpet area: 1800 sq.ft. (167.23 sq.m.)           4
Carpet area: 481.73 (44.75 sq.m.)                                                                                                4
Carpet area: 1180 (109.63 sq.m.)                                                                                                 3
Super Built up area 576(53.51 sq.m.)                                                                                             3
Carpet area: 554.16 (51.48 sq.m.)                                                                                                3
Super Built up area 2125(197.42 sq.m.)                                                                                           3
Carpet area: 685 (63.64 sq.m.)                                                                                                   3
Super Built up area 1743(161.93 sq.m.)                                                                                           3
Super Built up area 1298(120.59 sq.m.)                                                                                           3
Carpet area: 690 (64.1 sq.m.)                                                                                                    3
Super Built up area 2361(219.34 sq.m.)                                                                                           3
Built Up area: 2000 (185.81 sq.m.)                                                                                               3
Super Built up area 1283(119.19 sq.m.)Built Up area: 978.23 sq.ft. (90.88 sq.m.)Carpet area: 734.43 sq.ft. (68.23 sq.m.)         3
Carpet area: 531 (49.33 sq.m.)                                                                                                   3
Carpet area: 2298 (213.49 sq.m.)                                                                                                 3
Super Built up area 1929(179.21 sq.m.)                                                                                           3
Carpet area: 1075 (99.87 sq.m.)                                                                                                  3
Built Up area: 2400 (222.97 sq.m.)                                                                                               3
Carpet area: 710 (65.96 sq.m.)                                                                                                   3
Super Built up area 1735(161.19 sq.m.)                                                                                           3
Super Built up area 1671(155.24 sq.m.)                                                                                           3
Carpet area: 990 (91.97 sq.m.)                                                                                                   3
Carpet area: 1210 (112.41 sq.m.)                                                                                                 3
Carpet area: 2500 (232.26 sq.m.)                                                                                                 3
Carpet area: 3100 (288 sq.m.)                                                                                                    3
Super Built up area 735(68.28 sq.m.)                                                                                             3
Carpet area: 1385 (128.67 sq.m.)                                                                                                 3
Super Built up area 1620(150.5 sq.m.)                                                                                            3
Carpet area: 2100 (195.1 sq.m.)                                                                                                  3
Super Built up area 1295(120.31 sq.m.)                                                                                           3

In [21]:
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [23]:
df[df['bedRoom'].isna()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2849,2 BHK Flat in Sector 107 Gurgaon,signature global solera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2850,4 BHK Flat in Sector 53 Gurgaon,tulip monsella,NaN,33198.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2851,2 BHK Flat in New Palam Vihar,my home,NaN,4400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2852,2 BHK Flat in Sohna,breez global hill view,NaN,5470.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2922,3 BHK Flat in Sector 99A Gurgaon,pareena coban residences,NaN,5759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2923,1 BHK Flat in Golf Course Ext Road,ikon tower baani city centre,NaN,12437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2924,2 BHK Flat in Sector 89 Gurgaon,greenopolis,NaN,4820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2926,4 BHK Flat in C Block Sushant Lok Phase 1,maple heights,NaN,8888.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2927,2 BHK Flat in Sector 99 Gurgaon,assotech blith,NaN,6593.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df = df[~df['bedRoom'].isnull()]

In [25]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype('int');

In [26]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [27]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype('int');

In [28]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No','0');

In [30]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [31]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Servant Room,Study Room                            8
Study Room,Pooja Room                              8
Study Room,Servant Room,Store Room                 7
Pooja Room,Servant Room,Others                     6
Servant Room,Study Room,Pooja Room,Store Room      6
Pooja Room,Store Room                              6
Others,Servant Room                                6
Pooja Room,Others                                  6
Study Room,Servant Room,Others                     5
Pooja Room,Study Room,Store Room                   4
Pooja Room,Store Room,Study Room,Servant Room      4
Study Room,Pooja Room,Store Room                   3
Store Room,Servant Room                            3
Servant Room,Pooja Room,Study Room,Store Room      3
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Servant Room,Study Room,Store Room                 2
Study Room,Pooja Room,Servant Room                 2
Servant Room,Others,Store Room,Pooja Room          2
Pooja Room,Study Room,Others                       2
Store Room,Pooja Room,Servant Room                 1
Pooja Room,Study Room,Store Room,Servant Room      1
Pooja Room,Servant Room,Study Room,Store Room      1
Servant Room,Pooja Room,Store Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Study Room,Servant Room,Pooja Room                 1
Servant Room,Pooja Room,Store Room,Study Room      1
Study Room,Store Room                              1
Store Room,Study Room                              1
Servant Room,Pooja Room,Study Room                 1
Servant Room,Study Room,Pooja Room                 1
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [32]:
df['additionalRoom'].isna().sum()

np.int64(1305)

In [33]:
df['additionalRoom'].fillna('not avilable' , inplace = True)

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_3332\356664876.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('not avilable' , inplace = True)

In [35]:
df['additionalRoom'].isna().sum()

np.int64(0)

In [36]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [37]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not avilable,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not avilable,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not avilable,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [39]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0)

replacements = {
    'Ground': '0',
    'Basement': '-1', 
    'Lower': '0'
}

df['floorNum'] = df['floorNum'].replace(replacements)
df['floorNum'] = df['floorNum'].str.extract(r'(-?\d+)', expand=False)
df['floorNum'] = pd.to_numeric(df['floorNum'], errors='coerce').fillna(0).astype(int)

In [40]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not avilable,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not avilable,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not avilable,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [41]:
df['facing'].fillna('NA' , inplace = True);

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_3332\4203339280.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA' , inplace = True);

In [42]:
df['facing'].isna().sum()

np.int64(0)

In [43]:
df.insert(loc = 4 , column = 'area' , value = round((df['price']*10000000)/df['price_per_sqft']));

In [44]:
df.insert(loc = 1 , column = 'prooerty_type' , value = 'flat');

In [45]:
df.shape

(2997, 20)

In [46]:
df.to_csv('flats_cleaned.csv' , index = False);